sqlplus / as sysdba << EOF
spool dbcreationlog.txt
@$ORACLE_HOME/rdbms/admin/catalog.sql
@$ORACLE_HOME/rdbms/admin/catproc.sql
@$ORACLE_HOME/rdbms/admin/utlrp.sql
CREATE TABLESPACE GGS_DATA DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_GOLDEN_GATE_01.dbf' SIZE 50M AUTOEXTEND ON NEXT 8k BLOCKSIZE 8K;
CREATE TABLESPACE QUEUING DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_QUEUING_01.dbf' SIZE 50M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE TOOLS DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_TOOLS_01.dbf' SIZE 500M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE UNDOTBS DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_UNDO_02.dbf' SIZE 50M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE USERS DATAFILE 
  '/opt/oracle/oradata/SALCUS/USERS_01.dbf' SIZE 160M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_AQ DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_AQ_01.dbf' SIZE 300M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_01.dbf' SIZE 2000M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_BIG DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_BIG_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_BIG1 DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_BIG1_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_IVP DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_IVP_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_LOGS DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_LOGS_01.dbf' SIZE 200M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_MED DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_MED_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_DATA_SMALL DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_DATA_SMALL_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_IDS DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_IDS_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_INDEX DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_INDEX_01.dbf' SIZE 2000M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_INDEX_BIG DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_INDEX_BIG_01.dbf' SIZE 50M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE VANTIVE_INDEX_SMALL DATAFILE 
  '/opt/oracle/oradata/SALCUS/VANTIVE_INDEX_SMALL_01.dbf' SIZE 50M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
CREATE TABLESPACE XMLDB DATAFILE 
  '/opt/oracle/oradata/SALCUS/XMLDB.dbf' SIZE 10M AUTOEXTEND ON NEXT 8K BLOCKSIZE 8K;
shutdown immediate
startup
spool xdbinstall.log
@$ORACLE_HOME/rdbms/admin/catqm.sql xdb XMLDB TEMP YES
@$ORACLE_HOME/rdbms/admin/utlrp.sql
shutdown immediate
startup
spool recompile.log
@$ORACLE_HOME/rdbms/admin/utlrp.sql